<?php
return array (
  '<strong>Manage</strong> spaces' => '<strong>Manage</strong> coacting spaces',
  'Add new space' => 'Add new coacting space',
  'Change owner' => '',
  'Default Content Visiblity' => '',
  'Default Join Policy' => '',
  'Default Visibility' => '',
  'Default space' => 'Default coacting space',
  'Here you can define your default settings for new spaces. These settings can be overwritten for each individual space.' => 'Here you can define your default settings for new coacting spaces. These settings can be overwritten for each individual coacting space.',
  'Invalid space' => 'Invalid coacting space',
  'Manage members' => '',
  'Manage modules' => '',
  'Open space' => 'Open coacting space',
  'Overview' => '',
  'Search by name, description, id or owner.' => '',
  'Settings' => '',
  'Space Settings' => 'Coacting Space Settings',
  'Spaces' => 'Coacting Spaces',
  'This overview contains a list of each space with actions to view, edit and delete spaces.' => 'This overview contains a list of each coacting space with actions to view, edit and delete coacting spaces.',
);
