<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Activated' => '',
    'Configure' => '',
    'Delete' => '',
    'Disable' => '',
    'Enable' => '',
    'Members' => '',
    'Modules' => '',
    'Next' => '',
    'Security' => '',
    'Unarchive' => '',
    'never' => '',
    '-' => '',
    '<strong>Create</strong> new space' => '<strong>Create</strong> new coacting space',
    '<strong>Manage</strong> members' => '',
    '<strong>Members</strong>' => '',
    '<strong>Security</strong> settings' => '',
    '<strong>Space</strong> Modules' => '<strong>Coacting Space</strong> Modules',
    '<strong>Space</strong> settings' => '<strong>Coacting Space</strong> settings',
    'Actions' => '',
    'Add <strong>Modules</strong>' => '',
    'Advanced access settings' => '',
    'Archive' => '',
    'Are you sure, that you want to delete this space? All published content will be removed!' => 'Are you sure, that you want to delete this coacting space? All published content will be removed!',
    'Are you sure? *ALL* module data for this space will be deleted!' => 'Are you sure? *ALL* module data for this coacting space will be deleted!',
    'As owner of this space you can transfer this role to another administrator in space.' => 'As owner of this coacting space you can transfer this role to another administrator in coacting space.',
    'Cancel Membership' => '',
    'Choose if new content should be public or private by default' => '',
    'Choose the kind of membership you want to provide for this workspace.' => '',
    'Choose the security level for this workspace to define the visibleness.' => '',
    'Currently there are no modules available for this space!' => 'Currently there are no modules available for this coacting space!',
    'Don\'t receive notifications for new content' => '',
    'Enhance this space with modules.' => 'Enhance this coacting space with modules.',
    'Hide posts on dashboard' => 'Hide posts on News feed',
    'Invited By' => '',
    'Owner' => '',
    'Pending Approvals' => '',
    'Pending Invites' => '',
    'Permissions are assigned to different user-roles. To edit a permission, select the user-role you want to edit and change the drop-down value of the given permission.' => '',
    'Please type the name of the space to proceed.' => 'Please type the name of the coacting space to proceed.',
    'Receive Notifications for new content' => '',
    'Remove from space' => 'Remove from coacting space',
    'Role' => '',
    'Send & decline' => '',
    'Show all' => '',
    'Show posts on dashboard' => 'Show posts on news feed',
    'Space name' => 'Coacting Space name',
    'Space owner' => 'Coacting Space owner',
    'Stream (Default)' => '',
    'The url contains illegal characters!' => '',
    'This option will hide new content from this space at your dashboard' => 'This option will hide new content from this coacting space at your news feed',
    'This option will show new content from this space at your dashboard' => 'This option will show new content from this coacting space at your news feed',
    'Transfer ownership' => '',
    'e.g. example for {baseUrl}/s/example' => '',
    'space description' => 'coacting space description',
    'the default start page of this space for members' => 'the default start page of this coacting space for members',
    'the default start page of this space for visitors' => 'the default start page of this coacting space for visitors',
];
