<?php
return array (
  '<strong>Most recent</strong> activities' => '',
  '<strong>Posts</strong>' => '',
  '<strong>Profile Guide</strong>' => '',
  '<strong>Space</strong>' => '<strong>Coacting Space</strong>',
  '<strong>Space</strong> members' => '<strong>Coacting Space</strong> members',
  '<strong>Space</strong> navigation menu' => '<strong>Coacting Space</strong> navigation menu',
  '<strong>Space</strong> preferences' => '<strong>Coacting Space</strong> preferences',
  '<strong>Writing</strong> posts' => '',
  '<strong>Yay! You\'re done.</strong>' => '',
  'All users who are a member of this space will be displayed here.<br /><br />New members can be added by anyone who has been given access rights by the admin.' => 'All users who are a member of this coacting space will be displayed here.<br /><br />New members can be added by anyone who has been given access rights by the admin.',
  'New posts can be written and posted here.' => '',
  'Once you have joined or created a new space you can work on projects, discuss topics or just share information with other users.<br><br>There are various tools to personalize a space, thereby making the work process more productive.' => 'Once you have joined or created a new coacting space you can work on projects, discuss topics or just share information with other users.<br><br>There are various tools to personalize a coacting space, thereby making the work process more productive.',
  'That\'s it for the space guide.<br><br>To carry on with the user profile guide, click here: ' => 'That\'s it for the coacting space guide.<br><br>To carry on with the user profile guide, click here: ',
  'This is where you can navigate the space – where you find which modules are active or available for the particular space you are currently in. These could be polls, tasks or notes for example.<br><br>Only the space admin can manage the space\'s modules.' => 'This is where you can navigate the coacting space – where you find which modules are active or available for the particular coacting space you are currently in. These could be polls, tasks or notes for example.<br><br>Only the coacting space admin can manage the coacting space\'s modules.',
  'This menu is only visible for space admins. Here you can manage your space settings, add/block members and activate/deactivate tools for this space.' => 'This menu is only visible for coacting space admins. Here you can manage your coacting space settings, add/block members and activate/deactivate tools for this coacting space.',
  'To keep you up to date, other users\' most recent activities in this space will be displayed here.' => 'To keep you up to date, other users\' most recent activities in this coacting space will be displayed here.',
  'Yours, and other users\' posts will appear here.<br><br>These can then be liked or commented on.' => '',
);
