<?php
return array (
  '{displayName} created the new space {spaceName}' => '{displayName} created the new community {spaceName}',
  '{displayName} created this space.' => '{displayName} created this community.',
  '{displayName} joined the space {spaceName}' => '{displayName} joined the community {spaceName}',
  '{displayName} joined this space.' => '{displayName} joined this community.',
  '{displayName} left the space {spaceName}' => '{displayName} left the community {spaceName}',
  '{displayName} left this space.' => '{displayName} left this community.',
  '{spaceName} has been archived' => '',
  '{spaceName} has been unarchived' => '',
  '<strong>E-Mail</strong> Summaries' => '',
  '<strong>Latest</strong> activities' => '',
  'Activities' => '',
  'Daily' => '',
  'E-Mail Summaries' => '',
  'E-Mail summaries are sent to inform you about recent activities in the network.' => '',
  'E-Mail summaries are sent to users to inform them about recent activities in your network.' => '',
  'Exclude spaces below from the mail summary' => 'Exclude communities below from the mail summary',
  'Hourly' => '',
  'Interval' => '',
  'Latest news' => 'Последни новини',
  'Never' => '',
  'On this page you can configure the contents and the interval of these e-mail updates.' => '',
  'On this page you can define the default behavior for your users. These settings can be overwritten by users in their account settings page.' => '',
  'Only include spaces below to the mail summary' => 'Only include communities below to the mail summary',
  'Reset to defaults' => '',
  'See online:' => '',
  'Spaces' => 'Communities',
  'There are no activities yet.' => '',
  'Weekly' => '',
  'You will only receive an e-mail if there is something new.' => '',
  'Your daily summary' => '',
  'Your weekly summary' => '',
  'see online' => '',
  'via' => '',
  '{user1} now follows {user2}.' => '',
);
