<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Space has been archived' => 'Community has been archived',
    'Space has been unarchived' => 'Community has been unarchived',
    'Space member joined' => 'Community member joined',
    'Space member left' => 'Community member left',
    'Whenever a member leaves one of your spaces.' => 'Whenever a member leaves one of your communities.',
    'Whenever a new member joined one of your spaces.' => 'Whenever a new member joined one of your communities.',
    'Whenever a space is archived.' => 'Whenever a community is archived.',
    'Whenever a space is unarchived.' => 'Whenever a community is unarchived.',
];
